//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLBBWS.EDMS_WSSDK {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EDMS_WSSDK.WSSDKSoap")]
    public interface WSSDKSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckoutDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckoutDocument(string ProfileName, long RecId, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckinDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckinDocument(string WorkflowID, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportToDMS_from_mobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExportToDMS_from_mobile(string FileContent, string strFileName, string strProfile, string strFolderName, string ProfileValue, string userID, ref string error_code, ref string error_msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/K2Export", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string K2Export(string WorkflowID, ref string error_code, ref string error_msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadFolderList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.FolderInfo[] LoadFolderList(int UserId, int ParentId);
        
        // CODEGEN: Parameter 'FileContent' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Export", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.ExportResponse Export(HLBBWS.EDMS_WSSDK.ExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.DataProfileResult[] Search(string strCriteria, ref string error_code, ref string error_msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByDocID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.DataProfileResult[] SearchByDocID(int profileID, long docID, ref string error_code, ref string error_msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/K2ViewFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string K2ViewFile(string profile_name, string field_names, string field_keywords, ref string ImgURL, ref string error_msg);
        
        // CODEGEN: Parameter 'ProfileSearchResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProfileSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.ProfileSearchResponse ProfileSearch(HLBBWS.EDMS_WSSDK.ProfileSearchRequest request);
        
        // CODEGEN: Parameter 'ProfileSearchMobileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProfileSearchMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.ProfileSearchMobileResponse ProfileSearchMobile(HLBBWS.EDMS_WSSDK.ProfileSearchMobileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ViewFile(long VerID, long DocProfileID, short FileType, ref string fileURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewFileMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ViewFileMobile(long VerID, long DocProfileID, short FileType);
        
        // CODEGEN: Parameter 'FileContent' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Download", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.DownloadResponse Download(HLBBWS.EDMS_WSSDK.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTargetProfileValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateTargetProfileValue(long docID, string profile_name, string base_column_name, object base_value, string target_column_name, string target_value);
        
        // CODEGEN: Parameter 'ListDoc' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDocument_Multiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleResponse DeleteDocument_Multiple(HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteDocument(string docID, string profileID, string RequestorID, ref string error_code, ref string error_msg);
        
        // CODEGEN: Parameter 'LoadProfilesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.LoadProfilesResponse LoadProfiles(HLBBWS.EDMS_WSSDK.LoadProfilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginTest(string Username);
        
        // CODEGEN: Parameter 'dsAccess1' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.LoginResponse Login(HLBBWS.EDMS_WSSDK.LoginRequest request);
        
        // CODEGEN: Parameter 'LoadProfileFieldResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadProfileField", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.LoadProfileFieldResponse LoadProfileField(HLBBWS.EDMS_WSSDK.LoadProfileFieldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (Check_x0020_password) of message Check_x0020_password does not match the default value (fCheckChgPwd)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check password", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.Checkpassword1 fCheckChgPwd(HLBBWS.EDMS_WSSDK.Checkpassword request);
        
        // CODEGEN: Generating message contract since the wrapper name (Change_x0020_User_x0020_Password) of message Change_x0020_User_x0020_Password does not match the default value (fChgPwd)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Change User Password", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.ChangeUserPassword1 fChgPwd(HLBBWS.EDMS_WSSDK.ChangeUserPassword request);
        
        // CODEGEN: Generating message contract since the wrapper name (Return_x0020_Encrypted_x0020_Password) of message Return_x0020_Encrypted_x0020_Password does not match the default value (fGetEnPassword)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Return Encrypted Password", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword1 fGetEnPassword(HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword request);
        
        // CODEGEN: Generating message contract since the wrapper name (Return_x0020_Encrypted_x0020_String) of message Return_x0020_Encrypted_x0020_String does not match the default value (fEncryptString)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Return Encrypted String", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.ReturnEncryptedString1 fEncryptString(HLBBWS.EDMS_WSSDK.ReturnEncryptedString request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LogOut(string UserName, ref string Error_Msg, ref string Error_Code);
        
        // CODEGEN: Parameter 'fAccessControl_ArrResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fAccessControl_Arr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HLBBWS.EDMS_WSSDK.fAccessControl_ArrResponse fAccessControl_Arr(HLBBWS.EDMS_WSSDK.fAccessControl_ArrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewFile_with_Requestor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ViewFile_with_Requestor(long VerID, long ProfileID, short FileType, ref string fileURL, string RequestorID, ref string error_code, ref string error_msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewFile_with_Requestor_CustomeSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ViewFile_with_Requestor_CustomeSearch(long VerID, long ProfileID, short FileType, ref string fileURL, string RequestorID, ref string LocalFileName, ref string error_code, ref string error_msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string test(ref object a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewRptForProfileUsage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ViewRptForProfileUsage(string Datefrom, string DateTo, ref string error_code, ref string error_msg);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infoconnect.com.my")]
    public partial class FolderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int folderIdField;
        
        private string folderNameField;
        
        private string folderDescField;
        
        private string dateCreatedField;
        
        private string parentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
                this.RaisePropertyChanged("FolderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FolderName {
            get {
                return this.folderNameField;
            }
            set {
                this.folderNameField = value;
                this.RaisePropertyChanged("FolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FolderDesc {
            get {
                return this.folderDescField;
            }
            set {
                this.folderDescField = value;
                this.RaisePropertyChanged("FolderDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("ParentId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProfileField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int colIDField;
        
        private string colNameField;
        
        private string colDescField;
        
        private string colDataTypeField;
        
        private short dataLengthField;
        
        private bool compulsoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int colID {
            get {
                return this.colIDField;
            }
            set {
                this.colIDField = value;
                this.RaisePropertyChanged("colID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string colName {
            get {
                return this.colNameField;
            }
            set {
                this.colNameField = value;
                this.RaisePropertyChanged("colName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string colDesc {
            get {
                return this.colDescField;
            }
            set {
                this.colDescField = value;
                this.RaisePropertyChanged("colDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string colDataType {
            get {
                return this.colDataTypeField;
            }
            set {
                this.colDataTypeField = value;
                this.RaisePropertyChanged("colDataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Compulsory {
            get {
                return this.compulsoryField;
            }
            set {
                this.compulsoryField = value;
                this.RaisePropertyChanged("Compulsory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataColumnAccess : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupIdField;
        
        private string groupNameField;
        
        private string tranCodeField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("GroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TranCode {
            get {
                return this.tranCodeField;
            }
            set {
                this.tranCodeField = value;
                this.RaisePropertyChanged("TranCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataColumnAccessList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DataColumnAccess[] arr_DataValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DataColumnAccess[] Arr_DataValue {
            get {
                return this.arr_DataValueField;
            }
            set {
                this.arr_DataValueField = value;
                this.RaisePropertyChanged("Arr_DataValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Profiles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int profileIDField;
        
        private string profileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int profileID {
            get {
                return this.profileIDField;
            }
            set {
                this.profileIDField = value;
                this.RaisePropertyChanged("profileID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string profileName {
            get {
                return this.profileNameField;
            }
            set {
                this.profileNameField = value;
                this.RaisePropertyChanged("profileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsProfile_DocID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string profileIDField;
        
        private string docIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProfileID {
            get {
                return this.profileIDField;
            }
            set {
                this.profileIDField = value;
                this.RaisePropertyChanged("ProfileID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
                this.RaisePropertyChanged("DocID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DataColumn", Namespace="http://tempuri.org/")]
    public partial class DataColumn1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string col_DescField;
        
        private string profileValueField;
        
        private string col_IDField;
        
        private string col_NameField;
        
        private long fileSizeField;
        
        private string datecreatedField;
        
        private string authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Col_Desc {
            get {
                return this.col_DescField;
            }
            set {
                this.col_DescField = value;
                this.RaisePropertyChanged("Col_Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProfileValue {
            get {
                return this.profileValueField;
            }
            set {
                this.profileValueField = value;
                this.RaisePropertyChanged("ProfileValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Col_ID {
            get {
                return this.col_IDField;
            }
            set {
                this.col_IDField = value;
                this.RaisePropertyChanged("Col_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Col_Name {
            get {
                return this.col_NameField;
            }
            set {
                this.col_NameField = value;
                this.RaisePropertyChanged("Col_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Datecreated {
            get {
                return this.datecreatedField;
            }
            set {
                this.datecreatedField = value;
                this.RaisePropertyChanged("Datecreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DataProfileResult", Namespace="http://tempuri.org/")]
    public partial class DataProfileResult1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DataColumn1[] arr_DataValueField;
        
        private long verIDField;
        
        private long profileIDField;
        
        private long docIDField;
        
        private string imageNameField;
        
        private int totalRecFoundField;
        
        private long fileSizeField;
        
        private string datecreatedField;
        
        private string authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DataColumn1[] Arr_DataValue {
            get {
                return this.arr_DataValueField;
            }
            set {
                this.arr_DataValueField = value;
                this.RaisePropertyChanged("Arr_DataValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VerID {
            get {
                return this.verIDField;
            }
            set {
                this.verIDField = value;
                this.RaisePropertyChanged("VerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ProfileID {
            get {
                return this.profileIDField;
            }
            set {
                this.profileIDField = value;
                this.RaisePropertyChanged("ProfileID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
                this.RaisePropertyChanged("DocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImageName {
            get {
                return this.imageNameField;
            }
            set {
                this.imageNameField = value;
                this.RaisePropertyChanged("ImageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalRecFound {
            get {
                return this.totalRecFoundField;
            }
            set {
                this.totalRecFoundField = value;
                this.RaisePropertyChanged("TotalRecFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Datecreated {
            get {
                return this.datecreatedField;
            }
            set {
                this.datecreatedField = value;
                this.RaisePropertyChanged("Datecreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infoconnect.com.my")]
    public partial class DataColumn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string col_DescField;
        
        private string profileValueField;
        
        private string col_IDField;
        
        private string col_NameField;
        
        private long fileSizeField;
        
        private string datecreatedField;
        
        private string authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Col_Desc {
            get {
                return this.col_DescField;
            }
            set {
                this.col_DescField = value;
                this.RaisePropertyChanged("Col_Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProfileValue {
            get {
                return this.profileValueField;
            }
            set {
                this.profileValueField = value;
                this.RaisePropertyChanged("ProfileValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Col_ID {
            get {
                return this.col_IDField;
            }
            set {
                this.col_IDField = value;
                this.RaisePropertyChanged("Col_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Col_Name {
            get {
                return this.col_NameField;
            }
            set {
                this.col_NameField = value;
                this.RaisePropertyChanged("Col_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Datecreated {
            get {
                return this.datecreatedField;
            }
            set {
                this.datecreatedField = value;
                this.RaisePropertyChanged("Datecreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.infoconnect.com.my")]
    public partial class DataProfileResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DataColumn[] arr_DataValueField;
        
        private long verIDField;
        
        private long profileIDField;
        
        private long docIDField;
        
        private string imageNameField;
        
        private int totalRecFoundField;
        
        private long fileSizeField;
        
        private string datecreatedField;
        
        private string authorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DataColumn[] Arr_DataValue {
            get {
                return this.arr_DataValueField;
            }
            set {
                this.arr_DataValueField = value;
                this.RaisePropertyChanged("Arr_DataValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VerID {
            get {
                return this.verIDField;
            }
            set {
                this.verIDField = value;
                this.RaisePropertyChanged("VerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ProfileID {
            get {
                return this.profileIDField;
            }
            set {
                this.profileIDField = value;
                this.RaisePropertyChanged("ProfileID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long DocID {
            get {
                return this.docIDField;
            }
            set {
                this.docIDField = value;
                this.RaisePropertyChanged("DocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImageName {
            get {
                return this.imageNameField;
            }
            set {
                this.imageNameField = value;
                this.RaisePropertyChanged("ImageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalRecFound {
            get {
                return this.totalRecFoundField;
            }
            set {
                this.totalRecFoundField = value;
                this.RaisePropertyChanged("TotalRecFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long FileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
                this.RaisePropertyChanged("FileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Datecreated {
            get {
                return this.datecreatedField;
            }
            set {
                this.datecreatedField = value;
                this.RaisePropertyChanged("Datecreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Export", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strProfile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strFolderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] arrProfileValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string error_msg;
        
        public ExportRequest() {
        }
        
        public ExportRequest(byte[] FileContent, string strFileName, string strProfile, string strFolderName, string[] arrProfileValue, string userID, string error_code, string error_msg) {
            this.FileContent = FileContent;
            this.strFileName = strFileName;
            this.strProfile = strProfile;
            this.strFolderName = strFolderName;
            this.arrProfileValue = arrProfileValue;
            this.userID = userID;
            this.error_code = error_code;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExportResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error_msg;
        
        public ExportResponse() {
        }
        
        public ExportResponse(string ExportResult, string error_code, string error_msg) {
            this.ExportResult = ExportResult;
            this.error_code = error_code;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProfileSearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProfileSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string profile_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] column_names;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] column_keywords;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string RequestorID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string error_msg;
        
        public ProfileSearchRequest() {
        }
        
        public ProfileSearchRequest(string profile_name, string[] column_names, string[] column_keywords, string RequestorID, string error_code, string error_msg) {
            this.profile_name = profile_name;
            this.column_names = column_names;
            this.column_keywords = column_keywords;
            this.RequestorID = RequestorID;
            this.error_code = error_code;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProfileSearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProfileSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.DataProfileResult1[] ProfileSearchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error_msg;
        
        public ProfileSearchResponse() {
        }
        
        public ProfileSearchResponse(HLBBWS.EDMS_WSSDK.DataProfileResult1[] ProfileSearchResult, string error_code, string error_msg) {
            this.ProfileSearchResult = ProfileSearchResult;
            this.error_code = error_code;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProfileSearchMobile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProfileSearchMobileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string profile_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string column_desc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string column_data;
        
        public ProfileSearchMobileRequest() {
        }
        
        public ProfileSearchMobileRequest(string profile_name, string column_desc, string column_data) {
            this.profile_name = profile_name;
            this.column_desc = column_desc;
            this.column_data = column_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProfileSearchMobileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ProfileSearchMobileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.DataProfileResult1[] ProfileSearchMobileResult;
        
        public ProfileSearchMobileResponse() {
        }
        
        public ProfileSearchMobileResponse(HLBBWS.EDMS_WSSDK.DataProfileResult1[] ProfileSearchMobileResult) {
            this.ProfileSearchMobileResult = ProfileSearchMobileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long VerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long DocProfileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public short FileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContent;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(long VerID, long DocProfileID, short FileType, string FileName, byte[] FileContent) {
            this.VerID = VerID;
            this.DocProfileID = DocProfileID;
            this.FileType = FileType;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DownloadResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContent;
        
        public DownloadResponse() {
        }
        
        public DownloadResponse(string DownloadResult, string FileName, byte[] FileContent) {
            this.DownloadResult = DownloadResult;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDocument_Multiple", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDocument_MultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.clsProfile_DocID[] ListDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string RequestorID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string error_msg;
        
        public DeleteDocument_MultipleRequest() {
        }
        
        public DeleteDocument_MultipleRequest(HLBBWS.EDMS_WSSDK.clsProfile_DocID[] ListDoc, string RequestorID, string error_code, string error_msg) {
            this.ListDoc = ListDoc;
            this.RequestorID = RequestorID;
            this.error_code = error_code;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDocument_MultipleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDocument_MultipleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DeleteDocument_MultipleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string error_msg;
        
        public DeleteDocument_MultipleResponse() {
        }
        
        public DeleteDocument_MultipleResponse(string DeleteDocument_MultipleResult, string error_code, string error_msg) {
            this.DeleteDocument_MultipleResult = DeleteDocument_MultipleResult;
            this.error_code = error_code;
            this.error_msg = error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadProfiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadProfilesRequest {
        
        public LoadProfilesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadProfilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadProfilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.Profiles[] LoadProfilesResult;
        
        public LoadProfilesResponse() {
        }
        
        public LoadProfilesResponse(HLBBWS.EDMS_WSSDK.Profiles[] LoadProfilesResult) {
            this.LoadProfilesResult = LoadProfilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.DataColumnAccessList[] dsAccess1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Error_Msg;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string Username, string Password, HLBBWS.EDMS_WSSDK.DataColumnAccessList[] dsAccess1, string Error_code, string Error_Msg) {
            this.Username = Username;
            this.Password = Password;
            this.dsAccess1 = dsAccess1;
            this.Error_code = Error_code;
            this.Error_Msg = Error_Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.DataColumnAccessList[] dsAccess1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Error_Msg;
        
        public LoginResponse() {
        }
        
        public LoginResponse(string LoginResult, HLBBWS.EDMS_WSSDK.DataColumnAccessList[] dsAccess1, string Error_code, string Error_Msg) {
            this.LoginResult = LoginResult;
            this.dsAccess1 = dsAccess1;
            this.Error_code = Error_code;
            this.Error_Msg = Error_Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadProfileField", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadProfileFieldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int intProfileID;
        
        public LoadProfileFieldRequest() {
        }
        
        public LoadProfileFieldRequest(int intProfileID) {
            this.intProfileID = intProfileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadProfileFieldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadProfileFieldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.ProfileField[] LoadProfileFieldResult;
        
        public LoadProfileFieldResponse() {
        }
        
        public LoadProfileFieldResponse(HLBBWS.EDMS_WSSDK.ProfileField[] LoadProfileFieldResult) {
            this.LoadProfileFieldResult = LoadProfileFieldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check password", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Checkpassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string curUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Error_msg;
        
        public Checkpassword() {
        }
        
        public Checkpassword(string NewPassword, string curUser, string Error_msg) {
            this.NewPassword = NewPassword;
            this.curUser = curUser;
            this.Error_msg = Error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Check passwordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Checkpassword1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Check passwordResult")]
        public string CheckpasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Error_msg;
        
        public Checkpassword1() {
        }
        
        public Checkpassword1(string CheckpasswordResult, string Error_msg) {
            this.CheckpasswordResult = CheckpasswordResult;
            this.Error_msg = Error_msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Change User Password", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeUserPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string curPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string newPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Error_Msg;
        
        public ChangeUserPassword() {
        }
        
        public ChangeUserPassword(long UserID, string curPassword, string newPassword, string Error_code, string Error_Msg) {
            this.UserID = UserID;
            this.curPassword = curPassword;
            this.newPassword = newPassword;
            this.Error_code = Error_code;
            this.Error_Msg = Error_Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Change User PasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChangeUserPassword1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Change User PasswordResult")]
        public string ChangeUserPasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Error_code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Error_Msg;
        
        public ChangeUserPassword1() {
        }
        
        public ChangeUserPassword1(string ChangeUserPasswordResult, string Error_code, string Error_Msg) {
            this.ChangeUserPasswordResult = ChangeUserPasswordResult;
            this.Error_code = Error_code;
            this.Error_Msg = Error_Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Return Encrypted Password", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnEncryptedPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Password;
        
        public ReturnEncryptedPassword() {
        }
        
        public ReturnEncryptedPassword(string Password) {
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Return Encrypted PasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnEncryptedPassword1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Return Encrypted PasswordResult")]
        public string ReturnEncryptedPasswordResult;
        
        public ReturnEncryptedPassword1() {
        }
        
        public ReturnEncryptedPassword1(string ReturnEncryptedPasswordResult) {
            this.ReturnEncryptedPasswordResult = ReturnEncryptedPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Return Encrypted String", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnEncryptedString {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Password;
        
        public ReturnEncryptedString() {
        }
        
        public ReturnEncryptedString(string Password) {
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Return Encrypted StringResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnEncryptedString1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Return Encrypted StringResult")]
        public string ReturnEncryptedStringResult;
        
        public ReturnEncryptedString1() {
        }
        
        public ReturnEncryptedString1(string ReturnEncryptedStringResult) {
            this.ReturnEncryptedStringResult = ReturnEncryptedStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fAccessControl_Arr", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class fAccessControl_ArrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int intUser;
        
        public fAccessControl_ArrRequest() {
        }
        
        public fAccessControl_ArrRequest(int intUser) {
            this.intUser = intUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fAccessControl_ArrResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class fAccessControl_ArrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HLBBWS.EDMS_WSSDK.DataColumnAccessList[] fAccessControl_ArrResult;
        
        public fAccessControl_ArrResponse() {
        }
        
        public fAccessControl_ArrResponse(HLBBWS.EDMS_WSSDK.DataColumnAccessList[] fAccessControl_ArrResult) {
            this.fAccessControl_ArrResult = fAccessControl_ArrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSDKSoapChannel : HLBBWS.EDMS_WSSDK.WSSDKSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSDKSoapClient : System.ServiceModel.ClientBase<HLBBWS.EDMS_WSSDK.WSSDKSoap>, HLBBWS.EDMS_WSSDK.WSSDKSoap {
        
        public WSSDKSoapClient() {
        }
        
        public WSSDKSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSDKSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSDKSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSDKSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckoutDocument(string ProfileName, long RecId, string username) {
            return base.Channel.CheckoutDocument(ProfileName, RecId, username);
        }
        
        public string CheckinDocument(string WorkflowID, string Username) {
            return base.Channel.CheckinDocument(WorkflowID, Username);
        }
        
        public string ExportToDMS_from_mobile(string FileContent, string strFileName, string strProfile, string strFolderName, string ProfileValue, string userID, ref string error_code, ref string error_msg) {
            return base.Channel.ExportToDMS_from_mobile(FileContent, strFileName, strProfile, strFolderName, ProfileValue, userID, ref error_code, ref error_msg);
        }
        
        public string K2Export(string WorkflowID, ref string error_code, ref string error_msg) {
            return base.Channel.K2Export(WorkflowID, ref error_code, ref error_msg);
        }
        
        public HLBBWS.EDMS_WSSDK.FolderInfo[] LoadFolderList(int UserId, int ParentId) {
            return base.Channel.LoadFolderList(UserId, ParentId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.ExportResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.Export(HLBBWS.EDMS_WSSDK.ExportRequest request) {
            return base.Channel.Export(request);
        }
        
        public string Export(byte[] FileContent, string strFileName, string strProfile, string strFolderName, string[] arrProfileValue, string userID, ref string error_code, ref string error_msg) {
            HLBBWS.EDMS_WSSDK.ExportRequest inValue = new HLBBWS.EDMS_WSSDK.ExportRequest();
            inValue.FileContent = FileContent;
            inValue.strFileName = strFileName;
            inValue.strProfile = strProfile;
            inValue.strFolderName = strFolderName;
            inValue.arrProfileValue = arrProfileValue;
            inValue.userID = userID;
            inValue.error_code = error_code;
            inValue.error_msg = error_msg;
            HLBBWS.EDMS_WSSDK.ExportResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).Export(inValue);
            error_code = retVal.error_code;
            error_msg = retVal.error_msg;
            return retVal.ExportResult;
        }
        
        public HLBBWS.EDMS_WSSDK.DataProfileResult[] Search(string strCriteria, ref string error_code, ref string error_msg) {
            return base.Channel.Search(strCriteria, ref error_code, ref error_msg);
        }
        
        public HLBBWS.EDMS_WSSDK.DataProfileResult[] SearchByDocID(int profileID, long docID, ref string error_code, ref string error_msg) {
            return base.Channel.SearchByDocID(profileID, docID, ref error_code, ref error_msg);
        }
        
        public string K2ViewFile(string profile_name, string field_names, string field_keywords, ref string ImgURL, ref string error_msg) {
            return base.Channel.K2ViewFile(profile_name, field_names, field_keywords, ref ImgURL, ref error_msg);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.ProfileSearchResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.ProfileSearch(HLBBWS.EDMS_WSSDK.ProfileSearchRequest request) {
            return base.Channel.ProfileSearch(request);
        }
        
        public HLBBWS.EDMS_WSSDK.DataProfileResult1[] ProfileSearch(string profile_name, string[] column_names, string[] column_keywords, string RequestorID, ref string error_code, ref string error_msg) {
            HLBBWS.EDMS_WSSDK.ProfileSearchRequest inValue = new HLBBWS.EDMS_WSSDK.ProfileSearchRequest();
            inValue.profile_name = profile_name;
            inValue.column_names = column_names;
            inValue.column_keywords = column_keywords;
            inValue.RequestorID = RequestorID;
            inValue.error_code = error_code;
            inValue.error_msg = error_msg;
            HLBBWS.EDMS_WSSDK.ProfileSearchResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).ProfileSearch(inValue);
            error_code = retVal.error_code;
            error_msg = retVal.error_msg;
            return retVal.ProfileSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.ProfileSearchMobileResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.ProfileSearchMobile(HLBBWS.EDMS_WSSDK.ProfileSearchMobileRequest request) {
            return base.Channel.ProfileSearchMobile(request);
        }
        
        public HLBBWS.EDMS_WSSDK.DataProfileResult1[] ProfileSearchMobile(string profile_name, string column_desc, string column_data) {
            HLBBWS.EDMS_WSSDK.ProfileSearchMobileRequest inValue = new HLBBWS.EDMS_WSSDK.ProfileSearchMobileRequest();
            inValue.profile_name = profile_name;
            inValue.column_desc = column_desc;
            inValue.column_data = column_data;
            HLBBWS.EDMS_WSSDK.ProfileSearchMobileResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).ProfileSearchMobile(inValue);
            return retVal.ProfileSearchMobileResult;
        }
        
        public string ViewFile(long VerID, long DocProfileID, short FileType, ref string fileURL) {
            return base.Channel.ViewFile(VerID, DocProfileID, FileType, ref fileURL);
        }
        
        public string ViewFileMobile(long VerID, long DocProfileID, short FileType) {
            return base.Channel.ViewFileMobile(VerID, DocProfileID, FileType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.DownloadResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.Download(HLBBWS.EDMS_WSSDK.DownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public string Download(long VerID, long DocProfileID, short FileType, ref string FileName, ref byte[] FileContent) {
            HLBBWS.EDMS_WSSDK.DownloadRequest inValue = new HLBBWS.EDMS_WSSDK.DownloadRequest();
            inValue.VerID = VerID;
            inValue.DocProfileID = DocProfileID;
            inValue.FileType = FileType;
            inValue.FileName = FileName;
            inValue.FileContent = FileContent;
            HLBBWS.EDMS_WSSDK.DownloadResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).Download(inValue);
            FileName = retVal.FileName;
            FileContent = retVal.FileContent;
            return retVal.DownloadResult;
        }
        
        public string UpdateTargetProfileValue(long docID, string profile_name, string base_column_name, object base_value, string target_column_name, string target_value) {
            return base.Channel.UpdateTargetProfileValue(docID, profile_name, base_column_name, base_value, target_column_name, target_value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.DeleteDocument_Multiple(HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleRequest request) {
            return base.Channel.DeleteDocument_Multiple(request);
        }
        
        public string DeleteDocument_Multiple(HLBBWS.EDMS_WSSDK.clsProfile_DocID[] ListDoc, string RequestorID, ref string error_code, ref string error_msg) {
            HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleRequest inValue = new HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleRequest();
            inValue.ListDoc = ListDoc;
            inValue.RequestorID = RequestorID;
            inValue.error_code = error_code;
            inValue.error_msg = error_msg;
            HLBBWS.EDMS_WSSDK.DeleteDocument_MultipleResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).DeleteDocument_Multiple(inValue);
            error_code = retVal.error_code;
            error_msg = retVal.error_msg;
            return retVal.DeleteDocument_MultipleResult;
        }
        
        public string DeleteDocument(string docID, string profileID, string RequestorID, ref string error_code, ref string error_msg) {
            return base.Channel.DeleteDocument(docID, profileID, RequestorID, ref error_code, ref error_msg);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.LoadProfilesResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.LoadProfiles(HLBBWS.EDMS_WSSDK.LoadProfilesRequest request) {
            return base.Channel.LoadProfiles(request);
        }
        
        public HLBBWS.EDMS_WSSDK.Profiles[] LoadProfiles() {
            HLBBWS.EDMS_WSSDK.LoadProfilesRequest inValue = new HLBBWS.EDMS_WSSDK.LoadProfilesRequest();
            HLBBWS.EDMS_WSSDK.LoadProfilesResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).LoadProfiles(inValue);
            return retVal.LoadProfilesResult;
        }
        
        public string LoginTest(string Username) {
            return base.Channel.LoginTest(Username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.LoginResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.Login(HLBBWS.EDMS_WSSDK.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string Username, string Password, ref HLBBWS.EDMS_WSSDK.DataColumnAccessList[] dsAccess1, ref string Error_code, ref string Error_Msg) {
            HLBBWS.EDMS_WSSDK.LoginRequest inValue = new HLBBWS.EDMS_WSSDK.LoginRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.dsAccess1 = dsAccess1;
            inValue.Error_code = Error_code;
            inValue.Error_Msg = Error_Msg;
            HLBBWS.EDMS_WSSDK.LoginResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).Login(inValue);
            dsAccess1 = retVal.dsAccess1;
            Error_code = retVal.Error_code;
            Error_Msg = retVal.Error_Msg;
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.LoadProfileFieldResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.LoadProfileField(HLBBWS.EDMS_WSSDK.LoadProfileFieldRequest request) {
            return base.Channel.LoadProfileField(request);
        }
        
        public HLBBWS.EDMS_WSSDK.ProfileField[] LoadProfileField(int intProfileID) {
            HLBBWS.EDMS_WSSDK.LoadProfileFieldRequest inValue = new HLBBWS.EDMS_WSSDK.LoadProfileFieldRequest();
            inValue.intProfileID = intProfileID;
            HLBBWS.EDMS_WSSDK.LoadProfileFieldResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).LoadProfileField(inValue);
            return retVal.LoadProfileFieldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.Checkpassword1 HLBBWS.EDMS_WSSDK.WSSDKSoap.fCheckChgPwd(HLBBWS.EDMS_WSSDK.Checkpassword request) {
            return base.Channel.fCheckChgPwd(request);
        }
        
        public string fCheckChgPwd(string NewPassword, string curUser, ref string Error_msg) {
            HLBBWS.EDMS_WSSDK.Checkpassword inValue = new HLBBWS.EDMS_WSSDK.Checkpassword();
            inValue.NewPassword = NewPassword;
            inValue.curUser = curUser;
            inValue.Error_msg = Error_msg;
            HLBBWS.EDMS_WSSDK.Checkpassword1 retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).fCheckChgPwd(inValue);
            Error_msg = retVal.Error_msg;
            return retVal.CheckpasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.ChangeUserPassword1 HLBBWS.EDMS_WSSDK.WSSDKSoap.fChgPwd(HLBBWS.EDMS_WSSDK.ChangeUserPassword request) {
            return base.Channel.fChgPwd(request);
        }
        
        public string fChgPwd(long UserID, string curPassword, string newPassword, ref string Error_code, ref string Error_Msg) {
            HLBBWS.EDMS_WSSDK.ChangeUserPassword inValue = new HLBBWS.EDMS_WSSDK.ChangeUserPassword();
            inValue.UserID = UserID;
            inValue.curPassword = curPassword;
            inValue.newPassword = newPassword;
            inValue.Error_code = Error_code;
            inValue.Error_Msg = Error_Msg;
            HLBBWS.EDMS_WSSDK.ChangeUserPassword1 retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).fChgPwd(inValue);
            Error_code = retVal.Error_code;
            Error_Msg = retVal.Error_Msg;
            return retVal.ChangeUserPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword1 HLBBWS.EDMS_WSSDK.WSSDKSoap.fGetEnPassword(HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword request) {
            return base.Channel.fGetEnPassword(request);
        }
        
        public string fGetEnPassword(string Password) {
            HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword inValue = new HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword();
            inValue.Password = Password;
            HLBBWS.EDMS_WSSDK.ReturnEncryptedPassword1 retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).fGetEnPassword(inValue);
            return retVal.ReturnEncryptedPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.ReturnEncryptedString1 HLBBWS.EDMS_WSSDK.WSSDKSoap.fEncryptString(HLBBWS.EDMS_WSSDK.ReturnEncryptedString request) {
            return base.Channel.fEncryptString(request);
        }
        
        public string fEncryptString(string Password) {
            HLBBWS.EDMS_WSSDK.ReturnEncryptedString inValue = new HLBBWS.EDMS_WSSDK.ReturnEncryptedString();
            inValue.Password = Password;
            HLBBWS.EDMS_WSSDK.ReturnEncryptedString1 retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).fEncryptString(inValue);
            return retVal.ReturnEncryptedStringResult;
        }
        
        public string LogOut(string UserName, ref string Error_Msg, ref string Error_Code) {
            return base.Channel.LogOut(UserName, ref Error_Msg, ref Error_Code);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EDMS_WSSDK.fAccessControl_ArrResponse HLBBWS.EDMS_WSSDK.WSSDKSoap.fAccessControl_Arr(HLBBWS.EDMS_WSSDK.fAccessControl_ArrRequest request) {
            return base.Channel.fAccessControl_Arr(request);
        }
        
        public HLBBWS.EDMS_WSSDK.DataColumnAccessList[] fAccessControl_Arr(int intUser) {
            HLBBWS.EDMS_WSSDK.fAccessControl_ArrRequest inValue = new HLBBWS.EDMS_WSSDK.fAccessControl_ArrRequest();
            inValue.intUser = intUser;
            HLBBWS.EDMS_WSSDK.fAccessControl_ArrResponse retVal = ((HLBBWS.EDMS_WSSDK.WSSDKSoap)(this)).fAccessControl_Arr(inValue);
            return retVal.fAccessControl_ArrResult;
        }
        
        public string ViewFile_with_Requestor(long VerID, long ProfileID, short FileType, ref string fileURL, string RequestorID, ref string error_code, ref string error_msg) {
            return base.Channel.ViewFile_with_Requestor(VerID, ProfileID, FileType, ref fileURL, RequestorID, ref error_code, ref error_msg);
        }
        
        public string ViewFile_with_Requestor_CustomeSearch(long VerID, long ProfileID, short FileType, ref string fileURL, string RequestorID, ref string LocalFileName, ref string error_code, ref string error_msg) {
            return base.Channel.ViewFile_with_Requestor_CustomeSearch(VerID, ProfileID, FileType, ref fileURL, RequestorID, ref LocalFileName, ref error_code, ref error_msg);
        }
        
        public string test(ref object a) {
            return base.Channel.test(ref a);
        }
        
        public System.Data.DataSet ViewRptForProfileUsage(string Datefrom, string DateTo, ref string error_code, ref string error_msg) {
            return base.Channel.ViewRptForProfileUsage(Datefrom, DateTo, ref error_code, ref error_msg);
        }
    }
}
