//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HLBBWS.LOADS_API {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsEIWSLosaAppBocImpServiceSoapBinding", Namespace="http://imp.boc.ws.thetasp.com/")]
    public partial class WsEIWSLosaAppBocImpService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoanApplicationInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PFDetailsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoanApplicantNameAndIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsEIWSLosaAppBocImpService() {
            this.Url = global::HLBBWS.Properties.Settings.Default.HLBBWS_LOADS_API_WsEIWSLosaAppBocImpService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoanApplicationInfoCompletedEventHandler LoanApplicationInfoCompleted;
        
        /// <remarks/>
        public event PFDetailsInfoCompletedEventHandler PFDetailsInfoCompleted;
        
        /// <remarks/>
        public event LoanApplicantNameAndIDCompletedEventHandler LoanApplicantNameAndIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://boc.ws.thetasp.com/", ResponseNamespace="http://boc.ws.thetasp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WsEIWSLosaAppLoanInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsEIWSLosaAppLoanInfo LoanApplicationInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] AppHeader AppHeader) {
            object[] results = this.Invoke("LoanApplicationInfo", new object[] {
                        AppHeader});
            return ((WsEIWSLosaAppLoanInfo)(results[0]));
        }
        
        /// <remarks/>
        public void LoanApplicationInfoAsync(AppHeader AppHeader) {
            this.LoanApplicationInfoAsync(AppHeader, null);
        }
        
        /// <remarks/>
        public void LoanApplicationInfoAsync(AppHeader AppHeader, object userState) {
            if ((this.LoanApplicationInfoOperationCompleted == null)) {
                this.LoanApplicationInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanApplicationInfoOperationCompleted);
            }
            this.InvokeAsync("LoanApplicationInfo", new object[] {
                        AppHeader}, this.LoanApplicationInfoOperationCompleted, userState);
        }
        
        private void OnLoanApplicationInfoOperationCompleted(object arg) {
            if ((this.LoanApplicationInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanApplicationInfoCompleted(this, new LoanApplicationInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://boc.ws.thetasp.com/", ResponseNamespace="http://boc.ws.thetasp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WsEIWSPfmDetailsInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsEIWSPfmDetailsInfo PFDetailsInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] WsEIWSLosaAppHeader AppHeader) {
            object[] results = this.Invoke("PFDetailsInfo", new object[] {
                        AppHeader});
            return ((WsEIWSPfmDetailsInfo)(results[0]));
        }
        
        /// <remarks/>
        public void PFDetailsInfoAsync(WsEIWSLosaAppHeader AppHeader) {
            this.PFDetailsInfoAsync(AppHeader, null);
        }
        
        /// <remarks/>
        public void PFDetailsInfoAsync(WsEIWSLosaAppHeader AppHeader, object userState) {
            if ((this.PFDetailsInfoOperationCompleted == null)) {
                this.PFDetailsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPFDetailsInfoOperationCompleted);
            }
            this.InvokeAsync("PFDetailsInfo", new object[] {
                        AppHeader}, this.PFDetailsInfoOperationCompleted, userState);
        }
        
        private void OnPFDetailsInfoOperationCompleted(object arg) {
            if ((this.PFDetailsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PFDetailsInfoCompleted(this, new PFDetailsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://boc.ws.thetasp.com/", ResponseNamespace="http://boc.ws.thetasp.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WsEIWSLosaLoanApplicantInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsEIWSLosaLoanApplicantInfo LoanApplicantNameAndID([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] WsEIWSLosaAppHeader AppHeader) {
            object[] results = this.Invoke("LoanApplicantNameAndID", new object[] {
                        AppHeader});
            return ((WsEIWSLosaLoanApplicantInfo)(results[0]));
        }
        
        /// <remarks/>
        public void LoanApplicantNameAndIDAsync(WsEIWSLosaAppHeader AppHeader) {
            this.LoanApplicantNameAndIDAsync(AppHeader, null);
        }
        
        /// <remarks/>
        public void LoanApplicantNameAndIDAsync(WsEIWSLosaAppHeader AppHeader, object userState) {
            if ((this.LoanApplicantNameAndIDOperationCompleted == null)) {
                this.LoanApplicantNameAndIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanApplicantNameAndIDOperationCompleted);
            }
            this.InvokeAsync("LoanApplicantNameAndID", new object[] {
                        AppHeader}, this.LoanApplicantNameAndIDOperationCompleted, userState);
        }
        
        private void OnLoanApplicantNameAndIDOperationCompleted(object arg) {
            if ((this.LoanApplicantNameAndIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoanApplicantNameAndIDCompleted(this, new LoanApplicantNameAndIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class AppHeader {
        
        private string agencyIdField;
        
        private string bizRefNoField;
        
        private string businessAreaField;
        
        private string dateField;
        
        private string processIdField;
        
        private string tranxIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string agencyId {
            get {
                return this.agencyIdField;
            }
            set {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bizRefNo {
            get {
                return this.bizRefNoField;
            }
            set {
                this.bizRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string businessArea {
            get {
                return this.businessAreaField;
            }
            set {
                this.businessAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string processId {
            get {
                return this.processIdField;
            }
            set {
                this.processIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tranxId {
            get {
                return this.tranxIdField;
            }
            set {
                this.tranxIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaLoanApplicant {
        
        private string appCustNameIDNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appCustNameIDNo {
            get {
                return this.appCustNameIDNoField;
            }
            set {
                this.appCustNameIDNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaLoanApplicantInfo {
        
        private WsEIWSLosaAppHeader appHeaderField;
        
        private WsEIWSLosaLoanApplicant[] loanApplicantsField;
        
        private string loanApptFullListField;
        
        private WsEIWSLosaResponseInfo respInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaAppHeader appHeader {
            get {
                return this.appHeaderField;
            }
            set {
                this.appHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WsEIWSLosaLoanApplicant[] loanApplicants {
            get {
                return this.loanApplicantsField;
            }
            set {
                this.loanApplicantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loanApptFullList {
            get {
                return this.loanApptFullListField;
            }
            set {
                this.loanApptFullListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaResponseInfo respInfo {
            get {
                return this.respInfoField;
            }
            set {
                this.respInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaAppHeader {
        
        private string agencyIdField;
        
        private string bizRefNoField;
        
        private string businessAreaField;
        
        private string dateField;
        
        private string processIdField;
        
        private string tranxIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string agencyId {
            get {
                return this.agencyIdField;
            }
            set {
                this.agencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bizRefNo {
            get {
                return this.bizRefNoField;
            }
            set {
                this.bizRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string businessArea {
            get {
                return this.businessAreaField;
            }
            set {
                this.businessAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string processId {
            get {
                return this.processIdField;
            }
            set {
                this.processIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tranxId {
            get {
                return this.tranxIdField;
            }
            set {
                this.tranxIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaResponseInfo {
        
        private string respCodeField;
        
        private string respDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string respDesc {
            get {
                return this.respDescField;
            }
            set {
                this.respDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSPfmDetailsInfo {
        
        private WsEIWSLosaAppHeader appHeaderField;
        
        private string developerNameField;
        
        private string phaseCodeField;
        
        private string phaseNameField;
        
        private string projectNameField;
        
        private WsEIWSLosaResponseInfo respInfoField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaAppHeader appHeader {
            get {
                return this.appHeaderField;
            }
            set {
                this.appHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string developerName {
            get {
                return this.developerNameField;
            }
            set {
                this.developerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string phaseCode {
            get {
                return this.phaseCodeField;
            }
            set {
                this.phaseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string phaseName {
            get {
                return this.phaseNameField;
            }
            set {
                this.phaseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaResponseInfo respInfo {
            get {
                return this.respInfoField;
            }
            set {
                this.respInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaLoanApplicantPersonnelInfo {
        //internal string priApplicantId;
        private string applicantAddr1Field;
        
        private string applicantAddr2Field;
        
        private string applicantAddr3Field;
        
        private string applicantAddrCityField;
        
        private string applicantAddrCountryField;
        
        private string applicantAddrPostcodeField;
        
        private string applicantAddrStateField;
        
        private string applicantEmailsField;
        
        private string applicantIDsField;
        
        private string applicantNamesCombineField;
        
        private string chargorIDsField;
        
        private string chargorNamesField;
        
        private string eStatementFlagIndField;
        
        private string guarantorIDsField;
        
        private string guarantorNamesField;
        
        private string priApplicantNameField;

        private string priApplicantIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddr1 {
            get {
                return this.applicantAddr1Field;
            }
            set {
                this.applicantAddr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddr2 {
            get {
                return this.applicantAddr2Field;
            }
            set {
                this.applicantAddr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddr3 {
            get {
                return this.applicantAddr3Field;
            }
            set {
                this.applicantAddr3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddrCity {
            get {
                return this.applicantAddrCityField;
            }
            set {
                this.applicantAddrCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddrCountry {
            get {
                return this.applicantAddrCountryField;
            }
            set {
                this.applicantAddrCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddrPostcode {
            get {
                return this.applicantAddrPostcodeField;
            }
            set {
                this.applicantAddrPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantAddrState {
            get {
                return this.applicantAddrStateField;
            }
            set {
                this.applicantAddrStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantEmails {
            get {
                return this.applicantEmailsField;
            }
            set {
                this.applicantEmailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantIDs {
            get {
                return this.applicantIDsField;
            }
            set {
                this.applicantIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string applicantNamesCombine {
            get {
                return this.applicantNamesCombineField;
            }
            set {
                this.applicantNamesCombineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string chargorIDs {
            get {
                return this.chargorIDsField;
            }
            set {
                this.chargorIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string chargorNames {
            get {
                return this.chargorNamesField;
            }
            set {
                this.chargorNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eStatementFlagInd {
            get {
                return this.eStatementFlagIndField;
            }
            set {
                this.eStatementFlagIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guarantorIDs {
            get {
                return this.guarantorIDsField;
            }
            set {
                this.guarantorIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guarantorNames {
            get {
                return this.guarantorNamesField;
            }
            set {
                this.guarantorNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string priApplicantName {
            get {
                return this.priApplicantNameField;
            }
            set {
                this.priApplicantNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string priApplicantId
        {
            get
            {
                return this.priApplicantIdField;
            }
            set
            {
                this.priApplicantIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaLoanGeneralInfo {
        
        private string appStatusField;
        
        private string branchAddr1Field;
        
        private string branchAddr2Field;
        
        private string branchAddr3Field;
        
        private string branchAddrCityField;
        
        private string branchAddrCountryField;
        
        private string branchAddrPostcodeField;
        
        private string branchAddrStateField;
        
        private string branchManagerEmailField;
        
        private string branchManagerNameField;
        
        private string closingBranchField;
        
        private string lendingTypeField;

        private string loAcceptanceDtField;

        //private System.DateTime loAcceptanceDtField;
        
        private bool loAcceptanceDtFieldSpecified;
        
        private string mortgageCenterCodeField;
        
        private string mortgageCenterEmailField;
        
        private string salesEmailField;
        
        private string salesNameField;
        
        private string solicitorAccountTypeField;
        
        private string solicitorAddr1Field;
        
        private string solicitorAddr2Field;
        
        private string solicitorAddr3Field;
        
        private string solicitorCityField;
        
        private string solicitorCodeField;

        private string solicitorFaxNbrField;
        private string solicitorTelNbrField;

        private string solicitorCountryField;
        
        private string solicitorEmailField;
        
        private string solicitorIntStatusField;
        
        private string solicitorNBRField;
        
        private string solicitorNameField;
        
        private string solicitorPostcodeField;
        
        private string solicitorStateField;
        
        private string topupLoanIndField;

        private string phaseCodeField;
        private string phaseNameField;
        private string unitParcelNoField;
        //private string spaValueField;
        private System.Nullable<decimal> spaValueField;

        private bool spaValueFieldSpecified;

        private string categoryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appStatus {
            get {
                return this.appStatusField;
            }
            set {
                this.appStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddr1 {
            get {
                return this.branchAddr1Field;
            }
            set {
                this.branchAddr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddr2 {
            get {
                return this.branchAddr2Field;
            }
            set {
                this.branchAddr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddr3 {
            get {
                return this.branchAddr3Field;
            }
            set {
                this.branchAddr3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddrCity {
            get {
                return this.branchAddrCityField;
            }
            set {
                this.branchAddrCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddrCountry {
            get {
                return this.branchAddrCountryField;
            }
            set {
                this.branchAddrCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddrPostcode {
            get {
                return this.branchAddrPostcodeField;
            }
            set {
                this.branchAddrPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchAddrState {
            get {
                return this.branchAddrStateField;
            }
            set {
                this.branchAddrStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchManagerEmail {
            get {
                return this.branchManagerEmailField;
            }
            set {
                this.branchManagerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string branchManagerName {
            get {
                return this.branchManagerNameField;
            }
            set {
                this.branchManagerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string closingBranch {
            get {
                return this.closingBranchField;
            }
            set {
                this.closingBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lendingType {
            get {
                return this.lendingTypeField;
            }
            set {
                this.lendingTypeField = value;
            }
        }

        /// <remarks/>
        ///  [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loAcceptanceDt
        {
       // public System.DateTime loAcceptanceDt {
            get {
                return this.loAcceptanceDtField;
            }
            set {
                this.loAcceptanceDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loAcceptanceDtSpecified {
            get {
                return this.loAcceptanceDtFieldSpecified;
            }
            set {
                this.loAcceptanceDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mortgageCenterCode {
            get {
                return this.mortgageCenterCodeField;
            }
            set {
                this.mortgageCenterCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mortgageCenterEmail {
            get {
                return this.mortgageCenterEmailField;
            }
            set {
                this.mortgageCenterEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string salesEmail {
            get {
                return this.salesEmailField;
            }
            set {
                this.salesEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string salesName {
            get {
                return this.salesNameField;
            }
            set {
                this.salesNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorAccountType {
            get {
                return this.solicitorAccountTypeField;
            }
            set {
                this.solicitorAccountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorAddr1 {
            get {
                return this.solicitorAddr1Field;
            }
            set {
                this.solicitorAddr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorAddr2 {
            get {
                return this.solicitorAddr2Field;
            }
            set {
                this.solicitorAddr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorAddr3 {
            get {
                return this.solicitorAddr3Field;
            }
            set {
                this.solicitorAddr3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorCity {
            get {
                return this.solicitorCityField;
            }
            set {
                this.solicitorCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorCode {
            get {
                return this.solicitorCodeField;
            }
            set {
                this.solicitorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string solicitorFaxNbr
        {
            get
            {
                return this.solicitorFaxNbrField;
            }
            set
            {
                this.solicitorFaxNbrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string solicitorTelNbr
        {
            get
            {
                return this.solicitorTelNbrField;
            }
            set
            {
                this.solicitorTelNbrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string phaseCode
        {
            get
            {
                return this.phaseCodeField;
            }
            set
            {
                this.phaseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string phaseName
        {
            get
            {
                return this.phaseNameField;
            }
            set
            {
                this.phaseNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string unitParcelNo
        {
            get
            {
                return this.unitParcelNoField;
            }
            set
            {
                this.unitParcelNoField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> spaValue
        {
            get
            {
                return this.spaValueField;
            }
            set
            {
                this.spaValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool spaValueSpecified
        {
            get
            {
                return this.spaValueFieldSpecified;
            }
            set
            {
                this.spaValueFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorCountry {
            get {
                return this.solicitorCountryField;
            }
            set {
                this.solicitorCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorEmail {
            get {
                return this.solicitorEmailField;
            }
            set {
                this.solicitorEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorIntStatus {
            get {
                return this.solicitorIntStatusField;
            }
            set {
                this.solicitorIntStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorNBR {
            get {
                return this.solicitorNBRField;
            }
            set {
                this.solicitorNBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorName {
            get {
                return this.solicitorNameField;
            }
            set {
                this.solicitorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorPostcode {
            get {
                return this.solicitorPostcodeField;
            }
            set {
                this.solicitorPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string solicitorState {
            get {
                return this.solicitorStateField;
            }
            set {
                this.solicitorStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string topupLoanInd {
            get {
                return this.topupLoanIndField;
            }
            set {
                this.topupLoanIndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaFacility {
        
        private string disbursementMannerField;
        
        private System.Nullable<decimal> facilityAmount1Field;
        
        private bool facilityAmount1FieldSpecified;
        
        private System.Nullable<decimal> facilityAmount2Field;
        
        private bool facilityAmount2FieldSpecified;
        
        private System.Nullable<decimal> facilityAmount3Field;
        
        private bool facilityAmount3FieldSpecified;
        
        private System.Nullable<decimal> facilityAmount4Field;
        
        private bool facilityAmount4FieldSpecified;
        
        private System.Nullable<int> gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        private string productName1Field;
        
        private string productName2Field;
        
        private string productName3Field;
        
        private string productName4Field;
        
        private string purposeCodeField;
        
        private System.Nullable<decimal> totFeesAmountField;
        
        private bool totFeesAmountFieldSpecified;
        
        private System.Nullable<decimal> totFinancingAmountField;
        
        private bool totFinancingAmountFieldSpecified;
        
        private System.Nullable<decimal> totFinancingAmountIncFlvmField;
        
        private bool totFinancingAmountIncFlvmFieldSpecified;
        
        private System.Nullable<decimal> totInsAmountField;
        
        private bool totInsAmountFieldSpecified;
        
        private System.Nullable<decimal> totValuationFeesField;
        
        private bool totValuationFeesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string disbursementManner {
            get {
                return this.disbursementMannerField;
            }
            set {
                this.disbursementMannerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> facilityAmount1 {
            get {
                return this.facilityAmount1Field;
            }
            set {
                this.facilityAmount1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facilityAmount1Specified {
            get {
                return this.facilityAmount1FieldSpecified;
            }
            set {
                this.facilityAmount1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> facilityAmount2 {
            get {
                return this.facilityAmount2Field;
            }
            set {
                this.facilityAmount2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facilityAmount2Specified {
            get {
                return this.facilityAmount2FieldSpecified;
            }
            set {
                this.facilityAmount2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> facilityAmount3 {
            get {
                return this.facilityAmount3Field;
            }
            set {
                this.facilityAmount3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facilityAmount3Specified {
            get {
                return this.facilityAmount3FieldSpecified;
            }
            set {
                this.facilityAmount3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> facilityAmount4 {
            get {
                return this.facilityAmount4Field;
            }
            set {
                this.facilityAmount4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facilityAmount4Specified {
            get {
                return this.facilityAmount4FieldSpecified;
            }
            set {
                this.facilityAmount4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productName1 {
            get {
                return this.productName1Field;
            }
            set {
                this.productName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productName2 {
            get {
                return this.productName2Field;
            }
            set {
                this.productName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productName3 {
            get {
                return this.productName3Field;
            }
            set {
                this.productName3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productName4 {
            get {
                return this.productName4Field;
            }
            set {
                this.productName4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purposeCode {
            get {
                return this.purposeCodeField;
            }
            set {
                this.purposeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> totFeesAmount {
            get {
                return this.totFeesAmountField;
            }
            set {
                this.totFeesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totFeesAmountSpecified {
            get {
                return this.totFeesAmountFieldSpecified;
            }
            set {
                this.totFeesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> totFinancingAmount {
            get {
                return this.totFinancingAmountField;
            }
            set {
                this.totFinancingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totFinancingAmountSpecified {
            get {
                return this.totFinancingAmountFieldSpecified;
            }
            set {
                this.totFinancingAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> totFinancingAmountIncFlvm {
            get {
                return this.totFinancingAmountIncFlvmField;
            }
            set {
                this.totFinancingAmountIncFlvmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totFinancingAmountIncFlvmSpecified {
            get {
                return this.totFinancingAmountIncFlvmFieldSpecified;
            }
            set {
                this.totFinancingAmountIncFlvmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> totInsAmount {
            get {
                return this.totInsAmountField;
            }
            set {
                this.totInsAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totInsAmountSpecified {
            get {
                return this.totInsAmountFieldSpecified;
            }
            set {
                this.totInsAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> totValuationFees {
            get {
                return this.totValuationFeesField;
            }
            set {
                this.totValuationFeesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totValuationFeesSpecified {
            get {
                return this.totValuationFeesFieldSpecified;
            }
            set {
                this.totValuationFeesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaCollateral {
        
        private System.Nullable<decimal> buildUpAreaField;
        
        private bool buildUpAreaFieldSpecified;
        
        private string developerCodeField;
        
        private string developerNameField;
        
        private string financingTypeField;
        
        private System.Nullable<decimal> landAreaField;
        
        private bool landAreaFieldSpecified;
        
        private string projectCodeField;
        
        private string projectNameField;
        
        private string propertyAddressField;
        
        private string propertyTypeField;
        
        private string requiredValReportIndField;
        
        private string titleDetailsField;
        
        private string valuerAccountNbrField;
        
        private string valuerAccountTypeField;
        
        private string valuerAddr1Field;
        
        private string valuerAddr2Field;
        
        private string valuerAddr3Field;
        
        private string valuerCityField;
        
        private string valuerCodeField;

        private string valuerFaxNbrField;

        private string valuerTelNbrField;

        private string valuerCountryField;
        
        private string valuerEmailField;
        
        private string valuerNameField;
        
        private string valuerPostcodeField;
        
        private string valuerStateField;
        
        private System.Nullable<decimal> verbalIndicativeValueField;
        
        private bool verbalIndicativeValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> buildUpArea {
            get {
                return this.buildUpAreaField;
            }
            set {
                this.buildUpAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buildUpAreaSpecified {
            get {
                return this.buildUpAreaFieldSpecified;
            }
            set {
                this.buildUpAreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string developerCode {
            get {
                return this.developerCodeField;
            }
            set {
                this.developerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string developerName {
            get {
                return this.developerNameField;
            }
            set {
                this.developerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string financingType {
            get {
                return this.financingTypeField;
            }
            set {
                this.financingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> landArea {
            get {
                return this.landAreaField;
            }
            set {
                this.landAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool landAreaSpecified {
            get {
                return this.landAreaFieldSpecified;
            }
            set {
                this.landAreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string projectName {
            get {
                return this.projectNameField;
            }
            set {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string propertyAddress {
            get {
                return this.propertyAddressField;
            }
            set {
                this.propertyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string propertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string requiredValReportInd {
            get {
                return this.requiredValReportIndField;
            }
            set {
                this.requiredValReportIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string titleDetails {
            get {
                return this.titleDetailsField;
            }
            set {
                this.titleDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerAccountNbr {
            get {
                return this.valuerAccountNbrField;
            }
            set {
                this.valuerAccountNbrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerAccountType {
            get {
                return this.valuerAccountTypeField;
            }
            set {
                this.valuerAccountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerAddr1 {
            get {
                return this.valuerAddr1Field;
            }
            set {
                this.valuerAddr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerAddr2 {
            get {
                return this.valuerAddr2Field;
            }
            set {
                this.valuerAddr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerAddr3 {
            get {
                return this.valuerAddr3Field;
            }
            set {
                this.valuerAddr3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerCity {
            get {
                return this.valuerCityField;
            }
            set {
                this.valuerCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerCode {
            get {
                return this.valuerCodeField;
            }
            set {
                this.valuerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string valuerFaxNbr
        {
            get
            {
                return this.valuerFaxNbrField;
            }
            set
            {
                this.valuerFaxNbrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string valuerTelNbr
        {
            get
            {
                return this.valuerTelNbrField;
            }
            set
            {
                this.valuerTelNbrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerCountry {
            get {
                return this.valuerCountryField;
            }
            set {
                this.valuerCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerEmail {
            get {
                return this.valuerEmailField;
            }
            set {
                this.valuerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerName {
            get {
                return this.valuerNameField;
            }
            set {
                this.valuerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerPostcode {
            get {
                return this.valuerPostcodeField;
            }
            set {
                this.valuerPostcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valuerState {
            get {
                return this.valuerStateField;
            }
            set {
                this.valuerStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> verbalIndicativeValue {
            get {
                return this.verbalIndicativeValueField;
            }
            set {
                this.verbalIndicativeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool verbalIndicativeValueSpecified {
            get {
                return this.verbalIndicativeValueFieldSpecified;
            }
            set {
                this.verbalIndicativeValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.ws.thetasp.com")]
    public partial class WsEIWSLosaAppLoanInfo {
        
        private WsEIWSLosaAppHeader appHeaderField;
        
        private WsEIWSLosaCollateral collateralsField;
        
        private WsEIWSLosaFacility facilitiesField;
        
        private WsEIWSLosaLoanGeneralInfo loanApplicationInfoField;
        
        private WsEIWSLosaLoanApplicantPersonnelInfo loanApptPersonnelInfoField;
        
        private WsEIWSLosaResponseInfo respInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaAppHeader appHeader {
            get {
                return this.appHeaderField;
            }
            set {
                this.appHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaCollateral collaterals {
            get {
                return this.collateralsField;
            }
            set {
                this.collateralsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaFacility facilities {
            get {
                return this.facilitiesField;
            }
            set {
                this.facilitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaLoanGeneralInfo loanApplicationInfo {
            get {
                return this.loanApplicationInfoField;
            }
            set {
                this.loanApplicationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaLoanApplicantPersonnelInfo loanApptPersonnelInfo {
            get {
                return this.loanApptPersonnelInfoField;
            }
            set {
                this.loanApptPersonnelInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WsEIWSLosaResponseInfo respInfo {
            get {
                return this.respInfoField;
            }
            set {
                this.respInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoanApplicationInfoCompletedEventHandler(object sender, LoanApplicationInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanApplicationInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanApplicationInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsEIWSLosaAppLoanInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsEIWSLosaAppLoanInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PFDetailsInfoCompletedEventHandler(object sender, PFDetailsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PFDetailsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PFDetailsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsEIWSPfmDetailsInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsEIWSPfmDetailsInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoanApplicantNameAndIDCompletedEventHandler(object sender, LoanApplicantNameAndIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoanApplicantNameAndIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoanApplicantNameAndIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsEIWSLosaLoanApplicantInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsEIWSLosaLoanApplicantInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591