//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HLBBWS.EAIWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.eai.hlb.com", ConfigurationName="EAIWebService.EAIDelegateBean")]
    public interface EAIDelegateBean {
        
        // CODEGEN: Parameter 'serviceRequestReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="serviceRequestReturn")]
        HLBBWS.EAIWebService.serviceRequestResponse serviceRequest(HLBBWS.EAIWebService.serviceRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.eai.hlb.com")]
    public partial class XmlHolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private bool securedContentField;
        
        private string userField;
        
        private string oIDField;
        
        private string passwordField;
        
        private bool securedPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool securedContent {
            get {
                return this.securedContentField;
            }
            set {
                this.securedContentField = value;
                this.RaisePropertyChanged("securedContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string OID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
                this.RaisePropertyChanged("OID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool securedPassword {
            get {
                return this.securedPasswordField;
            }
            set {
                this.securedPasswordField = value;
                this.RaisePropertyChanged("securedPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serviceRequest", WrapperNamespace="http://ws.eai.hlb.com", IsWrapped=true)]
    public partial class serviceRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.eai.hlb.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serviceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.eai.hlb.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HLBBWS.EAIWebService.XmlHolder xml;
        
        public serviceRequestRequest() {
        }
        
        public serviceRequestRequest(string serviceId, HLBBWS.EAIWebService.XmlHolder xml) {
            this.serviceId = serviceId;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serviceRequestResponse", WrapperNamespace="http://ws.eai.hlb.com", IsWrapped=true)]
    public partial class serviceRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.eai.hlb.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public HLBBWS.EAIWebService.XmlHolder serviceRequestReturn;
        
        public serviceRequestResponse() {
        }
        
        public serviceRequestResponse(HLBBWS.EAIWebService.XmlHolder serviceRequestReturn) {
            this.serviceRequestReturn = serviceRequestReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EAIDelegateBeanChannel : HLBBWS.EAIWebService.EAIDelegateBean, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EAIDelegateBeanClient : System.ServiceModel.ClientBase<HLBBWS.EAIWebService.EAIDelegateBean>, HLBBWS.EAIWebService.EAIDelegateBean {
        
        public EAIDelegateBeanClient() {
        }
        
        public EAIDelegateBeanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EAIDelegateBeanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAIDelegateBeanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAIDelegateBeanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HLBBWS.EAIWebService.serviceRequestResponse HLBBWS.EAIWebService.EAIDelegateBean.serviceRequest(HLBBWS.EAIWebService.serviceRequestRequest request) {
            return base.Channel.serviceRequest(request);
        }
        
        public HLBBWS.EAIWebService.XmlHolder serviceRequest(string serviceId, HLBBWS.EAIWebService.XmlHolder xml) {
            HLBBWS.EAIWebService.serviceRequestRequest inValue = new HLBBWS.EAIWebService.serviceRequestRequest();
            inValue.serviceId = serviceId;
            inValue.xml = xml;
            HLBBWS.EAIWebService.serviceRequestResponse retVal = ((HLBBWS.EAIWebService.EAIDelegateBean)(this)).serviceRequest(inValue);
            return retVal.serviceRequestReturn;
        }
    }
}
